import:
  - source: logstash-plugins/.ci:travis/travis.yml@1.x
    mode: deep_merge_append

before_install:
  - sudo apt install -y squid
  - netstat -plunt | grep 3128
  - sudo cp -f .ci/squid.conf /etc/squid/squid.conf
  - sudo service squid restart
  - sudo netstat -plunt

env:
  jobs:
    - SPEC_OPTS="--tag integration" LOGGER_LEVEL="logstash.inputs.twitter=debug" ELASTIC_STACK_VERSION=7.x
