dist: focal # 20.04 LTS
language: minimal

import:
  # NOTE: can not be used with dist: focal due docker-ce addon
  #- source: logstash-plugins/.ci:travis/travis.yml@1.x
  #  mode: deep_merge_append
  - logstash-plugins/.ci:travis/matrix.yml@1.x
  - logstash-plugins/.ci:travis/exec.yml@1.x

addons:
  apt:
    packages:
      - squid

before_install:
  #- sudo apt install -y squid
  - netstat -plunt | grep 3128
  - sudo cp -f .ci/squid.conf /etc/squid/squid.conf
  - sudo service squid restart
  - sudo netstat -plunt
  - curl "https://devdocs.io" --proxy http://127.0.0.1:3128

env:
  jobs:
    - SPEC_OPTS="--tag integration" LOGGER_LEVEL="logstash.inputs.twitter=debug" ELASTIC_STACK_VERSION=7.x
