---
sudo: false
language: ruby
cache: bundler
rvm:
- jruby-1.7.25
script:
- bundle exec rspec spec --order rand
- bundle exec rspec spec --order rand -t integration
jdk: oraclejdk8
before_install: []
